'use strict';
const $=id=>document.getElementById(id),canvas=$('pitch'),ctx=canvas.getContext('2d'),game=new GoofyMatch();
let state='home',last=0,w=0,h=0,particles=[],toastUntil=0,keys={},sound=false,audio,best=0;
try{best=Math.max(0,parseInt(localStorage.getItem('gg-best')||'0',10)||0);sound=localStorage.getItem('gg-sound')==='true';}catch{}
function persist(key,value){try{localStorage.setItem(key,String(value));}catch{}}
function soundLabel(){$('sound').textContent=sound?'♪ ON':'♪ OFF';$('sound').setAttribute('aria-label',sound?'Turn sound off':'Turn sound on');}soundLabel();
function tone(freq,duration=.1){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();let osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.type='sine';osc.frequency.setValueAtTime(freq,audio.currentTime);gain.gain.setValueAtTime(.07,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.start();osc.stop(audio.currentTime+duration);}catch{}}
function screens(){for(const id of ['home','paused','result'])$(id).hidden=state!==id;$('pause').hidden=!['playing','paused'].includes(state);$('hint').textContent=state==='playing'?'← SLIDE TO SAVE →':'YOUR GLOVE. YOUR GLORY.';}
function updateHUD(){$('score').textContent=String(game.score).padStart(2,'0');$('best').textContent=String(best).padStart(2,'0');$('time').innerHTML=game.practice?'∞':`${Math.ceil(game.time)}<span>s</span>`;$('modeLabel').textContent=game.practice?'NO-PRESSURE WARM-UP':'60 SECOND SHOWDOWN';$('streak').textContent=state==='playing'?`${game.multiplier}× POINTS  ·  ${game.streak} IN A ROW`:'';}
function start(practice=false){game.reset(practice);particles=[];state='playing';$('toast').textContent='';screens();updateHUD();tone(540);}
function pause(){if(state==='playing'){state='paused';screens();}}function resume(){if(state==='paused'){state='playing';last=performance.now();screens();}}
function finish(){state='result';$('toast').textContent='';const record=game.score>best;if(record){best=game.score;persist('gg-best',best);}$('verdict').textContent=record?'NEW PERSONAL BEST':'FULL TIME';$('resultTitle').innerHTML=game.score>=80?'ABSOLUTE<br>WALL.':game.score>=30?'SAFE<br>HANDS.':'BEAUTIFUL<br>CHAOS.';$('finalScore').textContent=game.score;$('resultStats').textContent=`${game.saves} saves · ${game.stars} stars · ${game.boots} boots caught`;screens();tone(740,.25);}
$('play').onclick=()=>start();$('practice').onclick=()=>start(true);$('again').onclick=()=>start();$('pause').onclick=()=>state==='paused'?resume():pause();$('resume').onclick=resume;
function home(){state='home';game.reset();particles=[];$('toast').textContent='';screens();updateHUD();}$('quit').onclick=home;$('homeButton').onclick=home;
$('sound').onclick=()=>{sound=!sound;persist('gg-sound',sound);soundLabel();tone(640);};$('info').onclick=()=>{pause();$('help').showModal();};$('closeHelp').onclick=()=>$('help').close();$('resetBest').onclick=()=>{best=0;persist('gg-best',0);updateHUD();$('resetBest').textContent='Best score reset';};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>{keys={};pause();});
function move(e){if(state!=='playing')return;const rect=canvas.getBoundingClientRect();game.player=Math.max(.09,Math.min(.91,(e.clientX-rect.left)/rect.width));}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);move(e);});canvas.addEventListener('pointermove',e=>{if(e.buttons||e.pointerType==='touch')move(e);});
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' '].includes(e.key)&&!$('help').open){e.preventDefault();keys[e.key]=true;if(e.key===' ')state==='playing'?pause():resume();}});window.addEventListener('keyup',e=>keys[e.key]=false);
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(3,window.devicePixelRatio||1);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);}new ResizeObserver(resize).observe(canvas);
function circle(x,y,r,fill){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();}
function ball(x,y,r,spin){ctx.save();ctx.translate(x,y);ctx.rotate(spin);circle(0,3,r+1,'#10251f55');circle(0,0,r,'#fff9e8');ctx.fillStyle='#18382d';ctx.beginPath();for(let i=0;i<5;i++){let a=i*Math.PI*2/5-Math.PI/2;ctx.lineTo(Math.cos(a)*r*.46,Math.sin(a)*r*.46);}ctx.closePath();ctx.fill();ctx.strokeStyle='#18382d';ctx.lineWidth=1.5;for(let i=0;i<5;i++){let a=i*Math.PI*2/5-Math.PI/2;ctx.beginPath();ctx.moveTo(Math.cos(a)*r*.45,Math.sin(a)*r*.45);ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);ctx.stroke();}ctx.restore();}
function glove(x,y){ctx.save();ctx.translate(x,y);ctx.rotate((game.player-.5)*.2);ctx.fillStyle='#10251f44';ctx.beginPath();ctx.ellipse(0,17,36,9,0,0,7);ctx.fill();ctx.strokeStyle='#10251f';ctx.lineWidth=3;ctx.fillStyle='#d8f56d';ctx.beginPath();ctx.roundRect(-24,-22,48,47,13);ctx.fill();ctx.stroke();for(let i=0;i<4;i++){ctx.beginPath();ctx.roundRect(-24+i*12,-42-(i===1?5:0),13,38,7);ctx.fill();ctx.stroke();}ctx.beginPath();ctx.roundRect(18,-17,16,31,8);ctx.fill();ctx.stroke();ctx.fillStyle='#fff4dc';ctx.fillRect(-24,19,48,13);ctx.strokeRect(-24,19,48,13);ctx.fillStyle='#10251f';ctx.font='900 13px Arial';ctx.textAlign='center';ctx.fillText('GG',0,7);ctx.restore();}
function draw(t){ctx.clearRect(0,0,w,h);ctx.fillStyle='#287859';ctx.fillRect(0,0,w,h);for(let i=0;i<8;i++){ctx.fillStyle=i%2?'#277355':'#2c8060';ctx.fillRect(0,i*h/8,w,h/8);}ctx.strokeStyle='#d4efcd45';ctx.lineWidth=2;ctx.strokeRect(w*.06,h*.04,w*.88,h*.91);ctx.beginPath();ctx.arc(w*.5,h*.24,w*.22,0,7);ctx.stroke();ctx.beginPath();ctx.moveTo(w*.06,h*.24);ctx.lineTo(w*.94,h*.24);ctx.stroke();ctx.fillStyle='#163f32';ctx.fillRect(w*.07,h*.85,w*.86,h*.14);ctx.strokeStyle='#f3f6da50';ctx.lineWidth=1;for(let i=0;i<=12;i++){ctx.beginPath();ctx.moveTo(w*(.07+i*.86/12),h*.85);ctx.lineTo(w*(.07+i*.86/12),h*.99);ctx.stroke();}for(let i=0;i<=4;i++){ctx.beginPath();ctx.moveTo(w*.07,h*(.85+i*.035));ctx.lineTo(w*.93,h*(.85+i*.035));ctx.stroke();}ctx.strokeStyle='#fff4dc';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(w*.07,h*.99);ctx.lineTo(w*.07,h*.85);ctx.lineTo(w*.93,h*.85);ctx.lineTo(w*.93,h*.99);ctx.stroke();
 if(state==='home'){ball(w*.77,h*.32,30,Math.sin(t*.0004));ball(w*.84,h*.62,20,-t*.0002);}else{for(const item of game.items){const x=item.x*w,y=item.y*h;if(item.type==='ball')ball(x,y,Math.max(13,w*.046),item.spin);else{ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(item.spin)*.3);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.max(30,w*.09)}px Arial`;ctx.fillText(item.type==='star'?'⭐':'🥾',0,0);ctx.restore();}}}glove(game.player*w,h*.84);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);circle(p.x*w,p.y*h,3,p.color);}ctx.globalAlpha=1;}
function loop(t){const dt=last?Math.min(.05,(t-last)/1000):0;last=t;if(state==='playing'){if(keys.ArrowLeft)game.player=Math.max(.09,game.player-dt*1.15);if(keys.ArrowRight)game.player=Math.min(.91,game.player+dt*1.15);for(const e of game.step(dt)){if(e.type==='end'){finish();break;}if(e.type!=='miss'){const label=e.type==='save'?`+${e.points} NICE HANDS`:e.type==='star'?`+${e.points} STAR POWER`:'-3 THAT’S A BOOT';$('toast').textContent=label;toastUntil=t+650;tone(e.type==='boot'?150:e.type==='star'?880:520,.12);for(let j=0;j<12;j++)particles.push({x:e.x,y:.81,vx:(Math.random()-.5)*.5,vy:-Math.random()*.4,life:1,color:e.type==='boot'?'#ffac70':'#d8f56d'});}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=dt*.5;p.life-=dt*2;}particles=particles.filter(p=>p.life>0);if(t>toastUntil)$('toast').textContent='';updateHUD();}draw(t);requestAnimationFrame(loop);}screens();updateHUD();requestAnimationFrame(loop);
